name: Commit Pipeline
on:
  push:
    branches:
      - main

env:
  SHOULD_EXECUTE_JOB: "true"
  SHOULD_EXECUTE_STEP: "false"
  SHOULD_EXECUTE_STEP_CONDITION: "RUN"

jobs:
  execute:
    name: Commit Pipeline
    runs-on: ubuntu-latest
    if: ${{ env.MY_CONDITION_VARIABLE }}
    steps:
      - name: Print Commit Information
        run: |
          echo "Commit made to branch '${{ github.ref }}'."
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Committed by: ${{ github.actor }}"

      - name: Conditional Step
        if: ${{ env.SHOULD_EXECUTE_STEP }}
        run: |
          echo "This step only runs when SHOULD_EXECUTE_STEP is true"
          echo "Current value is: ${{ env.SHOULD_EXECUTE_STEP }}"

      - name: Conditional Step
        if: ${{ env.SHOULD_EXECUTE_STEP_CONDITION == 'RUN' }}
        run: |
          echo "This step only runs when SHOULD_EXECUTE_STEP is true"
          echo "Current value is: ${{ env.SHOULD_EXECUTE_STEP }}"