name: Commit Multi-Stage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Run multi-stage commit script
        run: |
          echo "Running multi-stage build script"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Run multi-stage test script
        run: |
          echo "Running multi-stage test script"
          echo "This is a placeholder for actual test commands"

  security:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/release' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Run multi-stage security script
        run: |
          echo "Running multi-stage security script"
          echo "This is a placeholder for actual security checks"

  deploy:
    runs-on: ubuntu-latest
    needs: [ security, test ]
    # Do not use always() here to avoid running even after cancellation
    if: |
      !cancelled() && 
      needs.test.result == 'success' && 
      (needs.security.result == 'success' || needs.security.result == 'skipped')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Run multi-stage deploy script
        run: |
          echo "Running multi-stage deploy script"
          echo "This is a placeholder for actual deployment commands"