name: Commit Pipeline
on:
  push:

env:
  SHOULD_EXECUTE_JOB: "true"
  SHOULD_EXECUTE_STEP: "false"
  SHOULD_EXECUTE_STEP_CONDITION: "RUN"

jobs:
  execute:
    name: Commit Pipeline
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Print Commit Information
        run: |
          echo "Commit made to branch '${{ github.ref }}'."
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Committed by: ${{ github.actor }}"

      - name: Should Execute Step
        if: ${{ env.SHOULD_EXECUTE_STEP }}
        run: |
          echo "This step only runs when SHOULD_EXECUTE_STEP is true"
          echo "Current value is: ${{ env.SHOULD_EXECUTE_STEP }}"

      - name: Should Execute Step with Condition RUN
        if: ${{ env.SHOULD_EXECUTE_STEP_CONDITION == 'RUN' }}
        run: |
          echo "This step only runs when SHOULD_EXECUTE_STEP is true"
          echo "Current value is: ${{ env.SHOULD_EXECUTE_STEP }}"

      - name: Execute Only on Failure
        id: execute-on-failure
        if: failure()
        run: |
          echo "This step only runs if all previous steps were successful"
          echo "Previous step completed successfully!"

      - name: Run When Previous Skipped
        if: steps.execute-on-failure.outcome == 'skipped'
        run: |
          echo "The previous step was skipped, so this step runs instead"
          echo "Previous step outcome: ${{ steps.previous-step.outcome }}"